services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand:
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn ecommerce.ecommerce.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: e-commerce-package-2.onrender.com